twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        postRepository: '@App\Repository\PostRepository'
        archiveBuilder: '@App\Service\ArchiveBuilder'
        authorRepository: '@App\Repository\AuthorRepository'